### ISSUE TITLE
Initialization Procedures

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook_MobilePWA-Meta#2]
**Not ready for implementation yet.**

----

# Basic Overview

<img width="689" alt="Screen Shot 2019-06-20 at 10 16 56" src="https://user-images.githubusercontent.com/2139261/59841787-977b2500-9344-11e9-9730-ecb2dac71a0a.png">

**Comment by neruthes** [comment]
Wondering what would @yisiliu have to input.

**Comment by Tedko** [comment]
Close this one? Or? 
But some UX is better than the pure Js based solution now.

**Comment by neruthes** [comment]
This requirement is no longer relevant. Neither are we going to involve any native-based solution in 2020. Furthermore, this entire repo is archaic now.
