### ISSUE TITLE
[Bug]After user finishing on-boarding, they will be re-direct to official Fb App by the link

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook_MobilePWA-Meta#7]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/6687437/62149937-d8167880-b2ca-11e9-9ac0-74d80d894d25.gif)

Should replace the link of **You can use Maskbook now!** in PWA ver preventing the redirection to official Apps.

**Comment by MainasuK** [comment]
Fixed.
It's should not redirect in new release 1.0.0 (5)
